### ISSUE TITLE
Name weapons based on their model

### ISSUE THREAD

**Issue by UnknownLITE** [exyleio/exyleio#11]
As if now, weapons which are planned to be added are named upon their weapon category, such as sniper rifle, assault rifle, etc.
I recommend naming them as their respective models
For a sniper rifle, AWP, Kar98k, or M24, can be the names

This enables us to add weapons of the same category without arising confusion for players about weapon type, etc.

~~_issue/feature request templates when?_~~

**Comment by developomp** [comment]
I intentionally avoided using real weapon names because it removes a lot of freedom from experimenting its stats, and increases barrier to entry which is important for io games like this. Everyone should be able to join the game and immediately know what to do.

As for issue/feature request templates, it should be ready by tomorrow or the next day.
